language: android
android:
  components:

    # We call "tools" twice to get the latest Android SDK tools.
    - tools
    - platform-tools
    - tools

    # The SDK version used to compile this program. This is NOT the minimum requirement.
    - android-25

    # We need a specific version of BuildTools to get this working.
    - build-tools-25.0.0

    - ndk-bundle
